#!/usr/bin/env python3
"""
Quick test to verify the webhook signature fix works correctly.
This test verifies that the signature generated by WebhookNotifier
matches what the webhook_server expects.
"""

import json
import hmac
import hashlib
import time
import os
import sys

# Set up environment
os.environ['WEBHOOK_SECRET'] = 'test_secret_123'
os.environ['WEBHOOK_URL'] = 'http://localhost:8001/webhook'
os.environ['GITHUB_API_SPEC_URL'] = 'http://example.com/spec.json'

from webhook_notifier import WebhookNotifier

def verify_signature(timestamp, payload_str, signature, secret):
    """Verify signature using the same logic as webhook_server.py"""
    signature_message = f"{timestamp}.{payload_str}"
    expected_signature = hmac.new(
        secret.encode('utf-8'),
        signature_message.encode('utf-8'),
        hashlib.sha256
    ).hexdigest()
    
    return hmac.compare_digest(expected_signature, signature)

def test_signature():
    """Test that generated signature can be verified"""
    print("Testing webhook signature generation and verification...")
    
    # Create a notifier
    notifier = WebhookNotifier(
        webhook_url='http://localhost:8001/webhook',
        webhook_secret='test_secret_123'
    )
    
    # Create a sample diff result
    diff_result = {
        'breaking_changes': [
            {'id': 'test_change', 'text': 'A breaking change', 'level': 'error'}
        ],
        'changelog': '### Changes\n- Added new endpoint',
        'current_spec': {
            'openapi': '3.0.0',
            'info': {'title': 'Test API', 'version': '1.0.0'},
            'paths': {}
        },
        'has_breaking_changes': True,
        'summary': '1 breaking change detected'
    }
    
    # Prepare payload the same way WebhookNotifier does
    payload = notifier._prepare_payload(diff_result)
    
    # Serialize exactly the way WebhookNotifier does
    payload_str = json.dumps(payload, sort_keys=True)
    
    # Generate headers
    headers = notifier._generate_headers_with_payload(payload_str)
    
    # Extract timestamp and signature from headers
    timestamp = headers.get('X-Webhook-Timestamp')
    signature = headers.get('X-Webhook-Signature')
    
    print(f"  Timestamp: {timestamp}")
    print(f"  Signature: {signature[:20]}...")
    print(f"  Payload size: {len(payload_str)} bytes")
    
    # Verify the signature using the same logic as webhook_server
    is_valid = verify_signature(timestamp, payload_str, signature, 'test_secret_123')
    
    if is_valid:
        print("  ✓ Signature verification PASSED!")
        return True
    else:
        print("  ✗ Signature verification FAILED!")
        print(f"    Payload: {payload_str[:100]}...")
        return False

if __name__ == '__main__':
    success = test_signature()
    sys.exit(0 if success else 1)
